GET http://localhost:3000/articles

###

POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "sdfgsdfg",
  "category": "sdfgsdfg",
  "announce": "sdfgsdfg",
  "fullText": "sdfgsdfg"
}

###

# Post new comment
POST http://localhost:3000/articles/uO5j/comments
Content-Type: application/json

{
"text": "sdfsdf"
}

###
GET http://localhost:3000/search?query=продам

